{% set name = "libcusparse" %}
{% set version = "12.5.8.93" %}
{% set cuda_version = "12.8" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/{{ name }}/{{ platform }}/{{ name }}-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: aa535ceb56690518c89257d985b13d505f951e4bba7591dbfaa179fc2fff329e  # [linux64]
  sha256: bc8b28217581fdb1c979eac48b24d35a385c7ca778f70cf1257e7760a922d65e  # [aarch64]
  sha256: f13b243912d8b07cc0136ad3760cd351553c74c1b54b7a6dbedb1dcc98ee8eb5  # [win]

build:
  number: 1
  binary_relocation: false
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]
    - patchelf <0.18.0     # [linux]
    - binutils             # [linux]

outputs:
  - name: libcusparse
    build:
      runpath_whitelist: # [linux]
        - $ORIGIN # [linux]
      # Repacked binaries on linux aarch64 have flag DT_TLSDESC (GNU_HASH),
      # which is not supported by LIEF and can raise ValueError during
      # overlinking checks. Use specific patterns from files section.
      overlinking_ignore_patterns:  # [linux and aarch64]
        - "targets/sbsa-linux/lib/{{ name }}*.so*"  # [linux and aarch64]
        - "targets/sbsa-linux/lib/stubs/{{ name }}*.so*"  # [linux and aarch64]
        - "lib/{{ name }}*.so*"  # [linux and aarch64]
      # Don't touch nested libs
      ignore_prefix_files:
        - "targets/sbsa-linux/lib/{{ name }}*.so*"   # [linux]
    files:
      - lib/libcusparse.so.*                             # [linux]
      - targets/{{ target_name }}/lib/libcusparse*.so.*  # [linux]
      - Library\bin\cusparse*.dll                        # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
        - libnvjitlink
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_compatible("libnvjitlink", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      requires:
        - patchelf  # [linux]
      files:
        - test-rpath.sh
      commands:
        - test -L $PREFIX/lib/libcusparse.so.{{ version }}                                  # [linux]
        - test -L $PREFIX/lib/libcusparse.so.{{ version.split(".")[0] }}                    # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcusparse.so.{{ version.split(".")[0] }}  # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcusparse.so.{{ version }}                # [linux]
        - bash test-rpath.sh                                                                        # [linux]
        - if not exist %LIBRARY_BIN%\cusparse*.dll exit 1                                   # [win]
    about:
      home: https://developer.nvidia.com/cusparse
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA Sparse Matrix Library
      description: |
        cuSPARSE - Basic Linear Algebra for Sparse Matrices on NVIDIA GPUs
      doc_url: https://docs.nvidia.com/cuda/cusparse/index.html

  - name: libcusparse-dev
    build:
      run_exports:
        - {{ pin_subpackage("libcusparse", max_pin="x") }}
      # # Repacked binaries on linux aarch64 have flag DT_TLSDESC set (GNU_HASH), which is not supported by lief.
      # # This is a workaround to ignore the overlinking error for problematic libcusparse.so files.
      # overlinking_ignore_patterns: # [linux and aarch64]
      #   - "lib/libcusparse.so*"  # [linux and aarch64]
      #   - "targets/sbsa-linux/lib/libcusparse.so*"  # [linux and aarch64]
      # # conda_build.exceptions.RunPathError: runpaths check failed
      # # ERROR (libcusparse-dev,targets/*/lib/stubs/libcusparse.so): runpaths ['$ORIGIN'] found
      # # The stub files use $ORIGIN runpaths which are valid but flagged by conda-build
      # # This whitelist allows $ORIGIN runpaths in the stub files during build-time validation.
      # # Note: We have comprehensive rpath validation in test-rpath.sh that ensures all libraries
      # # have the correct $ORIGIN rpath for runtime compatibility.
      # runpath_whitelist: # [linux]
      #   - $ORIGIN  # [linux]
    files:
      - lib/libcusparse.so         # [linux]
      - lib/pkgconfig                                 # [linux]
      - targets/{{ target_name }}/include             # [linux]
      - targets/{{ target_name }}/lib/libcusparse.so  # [linux]
      - targets/{{ target_name }}/lib/stubs           # [linux]
      # Not shipping Fortran bindings (in src) on Windows for now
      - targets/{{ target_name }}/libcusparse/src     # [linux]
      - Library\include                             # [win]
      - Library\lib                                 # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
        - libnvjitlink
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_compatible("libnvjitlink", max_pin="x.x") }}
        - {{ pin_subpackage("libcusparse", exact=True) }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - libcusparse-static >={{ version }}  # [linux]
    test:
      commands:
        - test -L $PREFIX/lib/libcusparse.so                                                   # [linux]
        - test -f $PREFIX/lib/pkgconfig/cusparse*.pc                                           # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/cusparse.h                         # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcusparse.so                         # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/stubs/libcusparse.so                   # [linux]
        # These `src` files are only available on Linux x86_64 (not aarch64 or ppc64le)
        - test -f $PREFIX/targets/{{ target_name }}/libcusparse/src/cusparse_fortran.c         # [linux64]
        - test -f $PREFIX/targets/{{ target_name }}/libcusparse/src/cusparse_fortran.h         # [linux64]
        - test -f $PREFIX/targets/{{ target_name }}/libcusparse/src/cusparse_fortran_common.h  # [linux64]
        - if not exist %LIBRARY_INC%\cusparse.h exit 1                                         # [win]
        - if not exist %LIBRARY_LIB%\cusparse.lib exit 1                                       # [win]
    about:
      home: https://developer.nvidia.com/cusparse
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA Sparse Matrix Library
      description: |
        cuSPARSE - Basic Linear Algebra for Sparse Matrices on NVIDIA GPUs
      doc_url: https://docs.nvidia.com/cuda/cusparse/index.html

  - name: libcusparse-static
    build:
      skip: true  # [win]
    files:
      - targets/{{ target_name }}/lib/libcusparse_static.a
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
        - libnvjitlink-static
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_compatible("libnvjitlink-static", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcusparse_static.a
    about:
      home: https://developer.nvidia.com/cusparse
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: CUDA Sparse Matrix Library
      description: |
        cuSPARSE - Basic Linear Algebra for Sparse Matrices on NVIDIA GPUs
      doc_url: https://docs.nvidia.com/cuda/cusparse/index.html

about:
  home: https://developer.nvidia.com/cusparse
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: CUDA Sparse Matrix Library
  description: |
    cuSPARSE - Basic Linear Algebra for Sparse Matrices on NVIDIA GPUs
  doc_url: https://docs.nvidia.com/cuda/cusparse/index.html

extra:
  feedstock-name: libcusparse
  recipe-maintainers:
    - conda-forge/cuda
